### ISSUE TITLE
souvenirs is a great app but one more crash report

### ISSUE THREAD

**Issue by jkbentley4** [zorgluf/souvenirs-android#24]
```
type: crash
osVersion: google/raven/raven:14/UQ1A.240105.002/2024012600:user/release-keys
package: fr.nuage.souvenirs:30
process: fr.nuage.souvenirs
processUptime: 17705 + 207 ms
installer: com.android.packageinstaller

java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
	at fr.nuage.souvenirs.viewmodel.PageDiffUtilCallback.getOldListSize(PageDiffUtilCallback.java:19)
	at androidx.recyclerview.widget.DiffUtil.calculateDiff(DiffUtil.java:123)
	at androidx.recyclerview.widget.DiffUtil.calculateDiff(DiffUtil.java:105)
	at fr.nuage.souvenirs.view.PageEditAdapter.setPages(PageEditAdapter.java:54)
	at fr.nuage.souvenirs.view.EditPageFragment.lambda$onCreateView$4$fr-nuage-souvenirs-view-EditPageFragment(EditPageFragment.java:153)
	at fr.nuage.souvenirs.view.EditPageFragment$$ExternalSyntheticLambda12.onChanged(Unknown Source:4)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
	at androidx.lifecycle.Transformations$1.onChanged(Transformations.java:76)
	at androidx.lifecycle.MediatorLiveData$Source.onChanged(MediatorLiveData.java:152)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:146)
	at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:468)
	at androidx.lifecycle.LiveData.observeForever(LiveData.java:234)
	at androidx.lifecycle.MediatorLiveData$Source.plug(MediatorLiveData.java:141)
	at androidx.lifecycle.MediatorLiveData.onActive(MediatorLiveData.java:118)
	at androidx.lifecycle.LiveData.changeActiveCounter(LiveData.java:390)
	at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:466)
	at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:425)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
	at androidx.fragment.app.FragmentViewLifecycleOwner.handleLifecycleEvent(FragmentViewLifecycleOwner.java:88)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:3060)
	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:587)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:279)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
```
Thank you!

**Comment by zorgluf** [comment]
Thanks for reporting.
But for this one I am kind of stuck... don't know how it can be possible to have this kind of error.
Could you give me more context ? When it happens ? It will help me identify the buggy pattern. Thanks.

**Comment by jkbentley4** [comment]
The crash happens after I start a new album, type in the title and then try to add a page. If I type in the title, edit the title and then add a page iy does not crash.
Hopefully this will help.

-------- Original Message --------
