### ISSUE TITLE
crashing when I try to add another photo

### ISSUE THREAD

**Issue by jkbentley4** [zorgluf/souvenirs-android#27]
```
type: crash
osVersion: google/raven/raven:14/AP1A.240505.004/2024051500:user/release-keys
package: fr.nuage.souvenirs:33
process: fr.nuage.souvenirs
processUptime: 539 + 247 ms
installer: org.fdroid.fdroid

java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.nuage.souvenirs/fr.nuage.souvenirs.AlbumListActivity}: android.view.InflateException: Binary XML file line #34 in fr.nuage.souvenirs:layout/activity_album_list: Binary XML file line #34 in fr.nuage.souvenirs:layout/activity_album_list: Error inflating class fragment
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3957)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4137)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:108)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:195)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:157)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:90)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2551)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: android.view.InflateException: Binary XML file line #34 in fr.nuage.souvenirs:layout/activity_album_list: Binary XML file line #34 in fr.nuage.souvenirs:layout/activity_album_list: Error inflating class fragment
Caused by: android.view.InflateException: Binary XML file line #34 in fr.nuage.souvenirs:layout/activity_album_list: Error inflating class fragment
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'fr.nuage.souvenirs.viewmodel.PageViewModel fr.nuage.souvenirs.viewmodel.AlbumViewModel.getPage(java.util.UUID)' on a null object reference
	at fr.nuage.souvenirs.view.EditPageFragment.onCreate(EditPageFragment.java:92)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3094)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:504)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:268)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
	at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2941)
	at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1989)
	at androidx.fragment.app.Fragment.onCreate(Fragment.java:1967)
	at androidx.navigation.fragment.NavHostFragment.onCreate(NavHostFragment.kt:163)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3094)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:504)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:268)
	at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:142)
	at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:136)
	at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:247)
	at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:226)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:957)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:885)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:849)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1011)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:972)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:570)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:462)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:413)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:775)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:197)
	at fr.nuage.souvenirs.AlbumListActivity.onCreate(AlbumListActivity.java:67)
	at android.app.Activity.performCreate(Activity.java:8820)
	at android.app.Activity.performCreate(Activity.java:8798)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1524)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3939)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4137)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:108)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:195)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:157)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:90)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2551)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
```

**Comment by zorgluf** [comment]
Thanks for the report. I see the origin of the crash and will try to solve, but didn't manage to reproduce on my side. When does it happen ? When adding a photo to an empty album ? A large one ? Is it always happening ? Any context ?
Thanks for the informations.

**Comment by jkbentley4** [comment]
It usually crashes when I open a new album and try to add the first photo

**Comment by jkbentley4** [comment]
Thank you!
